import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Kinda Drinks",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  modal: React.ReactNode;
}

export default function RootLayout(props: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="bg-gray-900 min-h-screen text-gray-200">
        <header className="flex w-full justify-center pt-8">
          <h1 className="font-semibold text-5xl flex flex-col relative">
            <span className="absolute font-light -left-10 text-[120px] bottom-0 text-green-500">
              {"{"}
            </span>
            <span>kinda</span>
            <span className="text-green-500">drinks</span>
          </h1>
        </header>
        {props.children}
        {props.modal}
      </body>
    </html>
  );
}
